# Generated by Django 2.2.19 on 2022-04-11 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220411_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='slug',
            new_name='url',
        ),
    ]
