# Generated by Django 2.2.19 on 2022-04-11 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220411_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='url',
            new_name='group',
        ),
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Group'),
        ),
    ]
